"""Generate the synthetic lab data: data/lab/sites.yaml and data/lab/DEMO-*.csv.

Run: uv run --frozen --no-sync python data/lab/generate.py
Seeded and idempotent (same seed, same bytes). Every value that sits near a criterion is derived from the loaded
criteria tables, never typed here. Edge cases are listed in docs/03-data.md and asserted in tests/test_screening.py.
"""
import csv
import random
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

from site_assess.screening import _band_contains, _load_criteria

SEED = 20261002
HEADER = (f"# SYNTHETIC DATA. Generated by data/lab/generate.py with seed {SEED}. Not real. "
          "Client names and addresses are fictional.")
LAB_DIR = Path(__file__).resolve().parent
COLUMNS = "site_id sample_id sampled_date depth_m matrix analyte cas_no result unit qualifier lor lab_ref".split()
D = Decimal

# limit of reporting per analyte (mg/kg)
LOR = {"Arsenic": "1", "Cadmium": "0.4", "Chromium (VI)": "1", "Copper": "1", "Lead": "5", "Mercury (inorganic)": "0.1",
       "Nickel": "1", "Zinc": "1", "Carcinogenic PAHs (as BaP TEQ)": "0.5", "Toluene": "0.1", "Ethylbenzene": "0.1",
       "Xylenes": "0.3", "Naphthalene": "0.5", "Benzene": "0.1", "F1": "10", "F2": "50", "Antimony": "0.5"}
CAS = {r["analyte"]: r["cas_no"] for s in ("hil-a-residential", "hsl-a-b-vapour-intrusion") for r in _load_criteria(s)}
CAS["Antimony"] = "7440-36-0"

SITES = """- site_id: DEMO-01
  client_name: "Example Holdings Pty Ltd"
  site_address: "12 Imaginary Street, Faketown NSW 2999"
  land_use: residential-a
  soil_type: sand
  story: "Clean residential lot. Zero exceedances; below-LOR and unknown-analyte rows are listed, not hidden."
- site_id: DEMO-02
  client_name: "Fictional Fuel Distributors Pty Ltd"
  site_address: "48 Notarealroad Avenue, Testville VIC 3999"
  land_use: residential-a
  soil_type: sand
  story: "Former fuel storage. Hydrocarbon hotspot in shallow soil, declining with depth; drives HSL band matching."
- site_id: DEMO-03
  client_name: "Sample Property Developments Pty Ltd"
  site_address: "7 Nowhere Lane, Mockford QLD 4999"
  land_use: residential-a
  also_screen_as: [commercial-d]
  soil_type: clay
  story: "Fill material with metals above residential HIL. A second run on the commercial HIL changes the result."
"""


def q2(x: D) -> D:
    return x.quantize(D("0.01"), rounding=ROUND_HALF_UP)


def fmt(x: D) -> str:
    return format(x.normalize(), "f")


def crit(set_id: str, analyte: str, band: int | None = None) -> D | None:
    """Criterion for an analyte; for HSL (band given) the value of the nth printed band; None when 'NL'."""
    rows = [r for r in _load_criteria(set_id) if r["analyte"] == analyte]
    r = rows[band or 0]
    return D(r["criterion"]) if r["criterion"] else None


def band_of(depth: D) -> int:
    bands = [r["depth_band"] for r in _load_criteria("hsl-a-b-vapour-intrusion") if r["analyte"] == "Toluene"]
    return next(i for i, b in enumerate(bands) if _band_contains(b, depth))


class Site:
    def __init__(self, site_id: str, date: str):
        self.id, self.date, self.rows, self.n = site_id, date, [], 0

    def add(self, sample, depth, analyte, value, *, unit="mg/kg", lor=None, lab_spelling=None, ref=None, detect=True):
        """One result row. A value below its LOR (or detect=False) becomes a '<' non-detect equal to the LOR."""
        lor = D(lor if lor is not None else LOR[analyte])
        value = q2(value)
        nd = value < lor or not detect
        self.rows.append([
            self.id, sample, self.date, "" if depth is None else depth, "soil", lab_spelling or analyte, CAS[analyte],
            fmt(lor if nd else value), unit, "<" if nd else "", fmt(lor), ref or f"SYN-{self.id}-{self.cert(sample)}",
        ])

    def cert(self, sample):
        self.certs = getattr(self, "certs", {})
        return f"{self.certs.setdefault(sample, len(self.certs) + 1):03d}"

    def write(self):
        with open(LAB_DIR / f"{self.id}.csv", "w", newline="") as f:
            f.write(HEADER + "\n")
            w = csv.writer(f, lineterminator="\n")
            w.writerow(COLUMNS)
            w.writerows(self.rows)


def demo01(rng):
    """Clean residential lot, HIL A: all detects well below criterion."""
    s, hil = Site("DEMO-01", "2026-03-10"), "hil-a-residential"
    analytes = [r["analyte"] for r in _load_criteria(hil)]
    for sample, depth in (("S01", "0.1"), ("S02", "0.5"), ("S03", "1.0"), ("S04", "1.5")):
        for a in analytes:
            v = crit(hil, a) * D(str(round(rng.uniform(0.05, 0.3), 3)))
            if (sample, a) == ("S04", "Lead"):
                v = crit(hil, a)  # exactly equal to the criterion: not an exceedance
            s.add(sample, depth, a, v, detect=(sample, a) != ("S03", "Cadmium"))  # S03 cadmium: below LOR
    s.add("S01", "0.1", "Antimony", D(str(round(rng.uniform(0.6, 3), 2))))  # no criterion in the set
    return s


def demo02(rng):
    """Former fuel storage, HSL A & B on sand: hotspot at BH01, boundary and unit edge cases."""
    s, hsl = Site("DEMO-02", "2026-04-02"), "hsl-a-b-vapour-intrusion"
    analytes = [r["analyte"] for r in _load_criteria(hsl) if r["depth_band"].startswith("0 m")]

    def base(a, depth):
        return crit(hsl, a, band_of(D(depth))) or crit(hsl, a, 0)  # NL band: scale off the shallow criterion

    hot = {"Benzene": 4, "Toluene": 1.5, "Ethylbenzene": 2, "Xylenes": 3, "Naphthalene": 5, "F1": 2.5, "F2": 1.5}
    parent = {}
    for depth, decay in (("0.5", 1), ("1.5", 0.45), ("3.0", 0.12), ("4.5", 0.03)):
        for a in analytes:
            v = base(a, depth) * D(str(hot[a] * decay))
            s.add(f"BH01-{depth}", depth, a, v)
            if depth == "0.5":
                parent[a] = v
    for a in analytes:  # field duplicate of BH01-0.5: independent result; toluene flips from over to under
        v = base(a, "0.5") * D("0.8") if a == "Toluene" else parent[a] * D("0.9")
        s.add("BH01-0.5-D", "0.5", a, v, ref="SYN-DEMO-02-001 (field duplicate of BH01-0.5)")
    for depth in ("0.5", "2.0"):  # clean location; benzene LOR above the criterion at 0.5 m
        for a in analytes:
            s.add(f"BH02-{depth}", depth, a, base(a, depth) * D(str(round(rng.uniform(0.05, 0.2), 3))),
                  lor=base(a, depth) * 2 if (a, depth) == ("Benzene", "0.5") else None,
                  detect=(a, depth) != ("Benzene", "0.5"))
    n = crit(hsl, "Naphthalene", 0) * D("1.5")  # reported in ug/kg while the criterion is mg/kg
    s.add("BH03-0.5", "0.5", "Naphthalene", n * 1000, unit="ug/kg", lor="500")
    c = [crit(hsl, "Xylenes", i) for i in range(4)]  # depth-band boundaries: same result either side of each
    for i, (lo, hi) in enumerate((("0.99", "1.0"), ("1.99", "2.0"), ("3.99", "4.0"))):
        mid = (c[i] + c[i + 1]) / 2
        s.add(f"BH04-{lo}", lo, "Xylenes", mid)
        s.add(f"BH04-{hi}", hi, "Xylenes", mid)
    s.add("BH05-0.5", "0.5", "Benzene", crit(hsl, "Benzene", 0) + D(LOR["Benzene"]))  # one increment over
    s.add("BH05-0.5", "0.5", "Toluene", crit(hsl, "Toluene", 0))  # exactly equal
    s.add("BH06-ND", None, "Toluene", crit(hsl, "Toluene", 0) / 2)  # no depth recorded
    return s


def demo03(rng):
    """Fill with metals: HIL A exceedances, alias spellings, an unconvertible unit; HIL D clears them."""
    s, hil = Site("DEMO-03", "2026-05-14"), "hil-a-residential"
    analytes = [r["analyte"] for r in _load_criteria(hil)]
    alias = {"Chromium (VI)": "Hexavalent Chromium", "Mercury (inorganic)": "Mercury",
             "Carcinogenic PAHs (as BaP TEQ)": "BaP TEQ"}
    # multiples of the HIL A criterion; everything not listed is a low background value
    over = {"FILL-02": {"Lead": "3.4", "Arsenic": "1.6", "Cadmium": "1.3", "Zinc": "1.1", "Mercury (inorganic)": "1.3",
                        "Carcinogenic PAHs (as BaP TEQ)": "2.2"}}
    for sample, depth in (("FILL-01", "0.2"), ("FILL-02", "0.4"), ("FILL-03", "0.6"), ("FILL-04", "0.8"),
                          ("FILL-05", "1.0")):
        for a in analytes:
            if (sample, a) == ("FILL-04", "Lead"):
                continue
            m = over.get(sample, {}).get(a) or str(round(rng.uniform(0.05, 0.35), 3))
            v = crit(hil, a) * D(m)
            if (sample, a) == ("FILL-03", "Lead"):
                v = crit(hil, a) + D(LOR[a])  # one reporting increment over
            s.add(sample, depth, a, v, lab_spelling=alias.get(a))
    s.add("FILL-04", "0.8", "Lead", D(str(round(rng.uniform(0.1, 0.5), 2))), unit="mg/L", lor="0.05")  # leachate unit
    return s


def main():
    rng = random.Random(SEED)
    for make in (demo01, demo02, demo03):
        make(rng).write()
    (LAB_DIR / "sites.yaml").write_text(HEADER + "\n" + SITES)


if __name__ == "__main__":
    main()
